### ISSUE TITLE
APK Download?

### ISSUE THREAD

**Issue by IzzySoft** [tomfong/simple-qr#40]
Did you consider making your app available for those without access to Play Store – e.g. by attaching the APK to tags/releases, or even bringing it to [F-Droid](https://f-droid.org/)? Thanks in advance!

**Comment by tomfong** [comment]
@IzzySoft Hi. I've already uploaded the apk to the [release](https://github.com/tomfong/simple-qr/releases) page. Please try.

Thx for your support.

**Comment by IzzySoft** [comment]
Thanks a lot! And apologies for the late reply, but Github notifications stopped reaching me (fixed now, hopefully). Looks great! I've just added your app to my repo (will [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.tomfong.simpleqr) with the next sync tomorrow), so be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to put next to the GooglePlay one and link it there :smiley:

If you want to bring your app to F-Droid.org itself, I can help you with that, too – but I'm not sure if the notification library you use might be a show-stopper there (t's using FCM I guess?).

**Comment by tomfong** [comment]
My app is developed in Ionic + Capacitor. To build the app, I also need to modify some Java codes after first building it by capacitor (see [this](https://github.com/tomfong/simple-qr#build-the-project-android)). For this case, is there any official way to deploy to F-Droid?

**Comment by IzzySoft** [comment]
AFAIK there are apps at F-Droid which use Ionic/Capacitor. I'm no developer, so I unfortunately cannot give you specifics on this.But I can give you some examples where I found capacitor mentioned: [Kubenav](https://github.com/kubenav/kubenav) (`io.kubenav.kubenav`), [Graphhopper](https://github.com/boldtrn/graphhopper-maps-capacitor) (`com.graphhopper.maps`), [OpenEar](https://github.com/ShacharHarshuv/open-ear) (`com.openear.www`) – oof, thatt's all I could find, but hopefully these are references useful to you.

(Ha! Good, Github notifications reaching my mailbox again :smiley:)

**Comment by tomfong** [comment]
I've removed the dependency that caused NonFreeNet issue since 2.6.3.1. Why the site still shows my app has NonFreeNet anti-feature?

I've also updated license but the site doesn't update.

![Screenshot_20220523-070820_Edge.jpg](https://user-images.githubusercontent.com/43058990/169720095-78110b40-131e-44e2-9260-8c7ac9897036.jpg)

Thank you.

**Comment by IzzySoft** [comment]
That is because those metadata need to be updated manually. Some of them (like Tracking or Ads) are detected automatically when they are gone, others (NonFreeDep and NonFreeNet) are not as they are not only defined by libraries (e.g. an app like Newpipe is pretty much useless without Youtube, even if it has no library indicating that). Similarly, licenses are hard to check for automatically.

Thanks to your notice, I've updated metadata for your app now. Changes will become visible with the next sync.

**Comment by tomfong** [comment]
If there's a thing I want to update next time, how can I find you?

Thank you.

**Comment by IzzySoft** [comment]
While you certainly could ping me here, or find the mail address via my website – I guess the easiest way would be to give it fully into your hands, I've just provided what I've set up with my repo via a PR. Fastlane is an established standard for app metadata, and once you know its structures (hints in the PR) it's easy to use, too.

Should you decide to merge, I'll enable it on my end to be checked whenever you make a new release, with changes pulled along. Should you for some reason require a metadata update "in between", just let me know and I can trigger it manually.

**Comment by IzzySoft** [comment]
Thanks for merging! And what I forgot to mention as means of contact: https://gitlab.com/IzzyOnDroid/repo/-/issues/ :smiley:

**Comment by tomfong** [comment]
I've updated the screenshots but the site is still showing some deleted images and the order looks incorrect.

Could you help?

**Comment by tomfong** [comment]
How can I remove the screenshots I don't want and reorder them?

**Comment by IzzySoft** [comment]
Which repo do you refer to? With my repo: Just go ahead. As long as you not only change the extension, the next update should reflect that in my repo. With F-Droid's repo: better do not. Long standing bug obviously nobody finds time to fix. Always make sure to re-use the names which are already there, as you cannot remove files unfortunately.

**Comment by tomfong** [comment]
The site seems to not update these days.

**Comment by IzzySoft** [comment]
Seeing your fresh RFP at F-Droid, you must be speaking about my site. Checking it, I don't follow: it has the latest release, and the screenshots have been updated properly. So can you please clarify what exactly you mean?

**Comment by tomfong** [comment]
this https://apt.izzysoft.de/fdroid/index/apk/com.tomfong.simpleqr

**Comment by IzzySoft** [comment]
And what seems not to update there? It has the latest version you've tagged, and the screenshots as well. Last update is shown as from 4 days ago. So what is wrong?

**Comment by tomfong** [comment]
The description

**Comment by IzzySoft** [comment]
Has letters.

Honestly, if you could write complete sentences describing what you miss, it would be much easier to figure what you might mean :wink: Currently I can only play a quiz with your words. So let me make a last guess: You've updated the description after the last release, and don't see that reflected. If it's that: works as designed. Fastlane is only pulled if there's a new release. Else you'd have no time preparing things properly – and your Fastlane might describe the next release, due in X days, confusing the users.

**Comment by tomfong** [comment]
haha my bad.

Thx for your help🙇🏻

**Comment by IzzySoft** [comment]
OK, glad I finally guessed right :rofl:
